### ISSUE TITLE
Trying to run dp-cgans

### ISSUE THREAD

**Issue by Rock910** [sunchang0124/dp_cgans#7]
Hi,
When I run: 
poetry run dp-cgans gen --gen-size=103463 '/content/drive/MyDrive/cps_ctgan.csv'
I get:
Model instantiated, fitting...
/content/dp_cgans/.venv/lib/python3.9/site-packages/sklearn/mixture/_base.py:286: ConvergenceWarning: Initialization 5 did not converge. Try different init parameters, or increase max_iter, tol or check for degenerate data.
  warnings.warn(
/content/dp_cgans/.venv/lib/python3.9/site-packages/sklearn/mixture/_base.py:286: ConvergenceWarning: Initialization 5 did not converge. Try different init parameters, or increase max_iter, tol or check for degenerate data.
  warnings.warn(
/content/dp_cgans/.venv/lib/python3.9/site-packages/sklearn/mixture/_base.py:286: ConvergenceWarning: Initialization 5 did not converge. Try different init parameters, or increase max_iter, tol or check for degenerate data.
  warnings.warn(
/content/dp_cgans/.venv/lib/python3.9/site-packages/sklearn/mixture/_base.py:286: ConvergenceWarning: Initialization 5 did not converge. Try different init parameters, or increase max_iter, tol or check for degenerate data.
  warnings.warn(
/content/dp_cgans/.venv/lib/python3.9/site-packages/sklearn/mixture/_base.py:286: ConvergenceWarning: Initialization 5 did not converge. Try different init parameters, or increase max_iter, tol or check for degenerate data.
  warnings.warn(
/content/dp_cgans/.venv/lib/python3.9/site-packages/sklearn/mixture/_base.py:286: ConvergenceWarning: Initialization 5 did not converge. Try different init parameters, or increase max_iter, tol or check for degenerate data.
  warnings.warn(
/content/dp_cgans/.venv/lib/python3.9/site-packages/sklearn/mixture/_base.py:286: ConvergenceWarning: Initialization 5 did not converge. Try different init parameters, or increase max_iter, tol or check for degenerate data.
  warnings.warn(
/content/dp_cgans/.venv/lib/python3.9/site-packages/sklearn/mixture/_base.py:286: ConvergenceWarning: Initialization 5 did not converge. Try different init parameters, or increase max_iter, tol or check for degenerate data.
  warnings.warn(
/content/dp_cgans/.venv/lib/python3.9/site-packages/sklearn/mixture/_base.py:286: ConvergenceWarning: Initialization 5 did not converge. Try different init parameters, or increase max_iter, tol or check for degenerate data.
  warnings.warn(
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/content/dp_cgans/src/dp_cgans/__main__.py", line 48, in cli_gen
    model.fit(tabular_data)

  File "/content/dp_cgans/src/dp_cgans/base.py", line 143, in fit
    self._fit(transformed)

  File "/content/dp_cgans/src/dp_cgans/dp_cgan_init.py", line 59, in _fit
    self._model.fit(

  File "/content/dp_cgans/src/dp_cgans/synthesizers/dp_cgan.py", line 438, in fit
    condvec_pair = self._data_sampler.sample_condvec_pair(self._batch_size)

  File "/content/dp_cgans/src/dp_cgans/data_sampler.py", line 269, in sample_condvec_pair
    converted_paired_discrete_column_id.append(self.pair_id_dict[tuple(self.get_position[np.sort(each)])])

KeyError: (0, 0)

Would you have any suggestions on how to proceed?

Thank you!

**Comment by sunchang0124** [comment]
Sorry for replying (very) late. We updated the package please feel free to try it again.
